### ISSUE TITLE
ArgoBus Business Cards

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#239] opened 2015-10-22 02:27 UTC
I know we chatted about having some extremely cool and memorable business cards (think there is a ticket on the Business Repo for that), but I want to have something to start handing out to people ASAP too, especially with me going to Kansas City Nov 4th for the CEO Nationals Conference. 

I was thinking about having this picture **as the entire business card background** with these new statements and with the general contact information

![argo cover photo](https://cloud.githubusercontent.com/assets/11848699/10655449/67d7854c-783a-11e5-9c8f-418d24295422.png)

--
Change Life should be an adventure to

## Be Brave. Take Risks. Create Memories. Nothing substitutes Experience

and Buy a ticket to

## Pledge. Share. Go, through Argo

**Comment by markstm17** [comment] 2015-10-22 02:50
What are your thoughts on the above ideas??

And for Contact Information this is what I was thinking. Please give thoughts on this too!

Either
- Only social media stuff and website 
 - Instagram
 - Twitter
 - Facebook
 - argobus.com

OR
- Personal Stuff
 - Trevor Marks/Duncan Graham
 - Cell Number
 - ArgoBus personal email
 - argobus.com

**Comment by markstm17** [comment] 2015-10-22 21:50
**Facebook**
- Argo Bus
- Argo

**Instagram**
- Argo_Bus

**Twitter**
- @argo_bus (Argo Bus)

**Comment by markstm17** [comment] 2015-10-22 21:53
@duncangraham Let's get this done today then. You make the graphic changes, post it on here and I'll handle getting both you and me our business cards ASAP, hopefully getting them sometime next week

I want to have this to pass out for when I'm down in Kansas City for the Entrepreneurial Conference Nov 4th-Nov 8th for people that I talk with, and I know it'll be beneficial for you to have as well. 

Do you think we should have general cards with the saying that I put above, or specific ones with both yours and my names on it??

**Comment by duncangraham** [comment] 2015-10-23 17:26
this is a dupe of https://github.com/ArgoBus/Business/issues/12, closing

**Closed by duncangraham** 2015-10-23 17:26 UTC
