### ISSUE TITLE
WHY do we need to "approve bus trips" as administrators through Argo? 

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#187] opened 2015-10-02 18:56 UTC
Relating to #186 

Initially maybe yes, we need this (the only reason I see WHY is because we need to get a quote and an actual cost of the bus behind the scenes)

But why not focus on giving a range per hour for the different types of vehicles, and our #167 can spit out the #135 and the #184 

Bus Range ($50-$70)
Motor Coach Range ($80-$110)
"Party Bus" Range ($100-$150)
Limo Range ($100-$150)

**Comment by markstm17** [comment] 2015-10-02 18:57
THEN

As administrators, (primarily me), I then get an email notification and it is my job to book the bus/coach/limo/etc..

**Comment by duncangraham** [comment] 2015-10-02 23:18
fuck yea. Lemme close some smaller, older tickets this weekend. Then lets talk monday about the bigger ones (like this) and determine priorities.

**Comment by duncangraham** [comment] 2015-10-02 23:34
this is a duplicate of #167, closing in favor of the original

**Closed by duncangraham** 2015-10-02 23:34 UTC
