### ISSUE TITLE
Fix Null, Null problem after confirmation screen after pledging for a trip

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#127] opened 2015-08-18 05:50 UTC
When I pledged tonight (8/17), I did NOT have my first or last name or cell phone saved until I filled them out on the CC processing page when pledging for a trip. 

My name did not register or get recognized on the next confirmation page (listed below) I did this via mobile.

![11910611_10154120236002598_1476801303_n](https://cloud.githubusercontent.com/assets/11848699/9323159/0aecd28a-4543-11e5-971b-b6811709c7d5.jpg)

**Comment by markstm17** [comment] 2015-08-20 01:48
I'm going to close this currently because I think things have been working fine so far as people have signed up

**Comment by markstm17** [comment] 2015-08-21 16:32
@duncangraham it seems like 85-90% of the people signing up aren't having problems and are properly getting their names signed up and putting their credit card info in correctly.

As the latest example, for the bus trip from Milwaukee (Ryley's bus), there is one person that the name went null, null. 

Their email is also not represented in Stripe and they are not a customer. 


We've got to look into how they are able to sign up and be approved through Argo without providing the correct information (or potentially a bad/old credit card?)

**Comment by duncangraham** [comment] 2015-08-24 18:01
this seems to be a dupe of #133 and the solution AFAIK is to add form validation. No one should be able to submit a form will faulty/missing info and then continue to the next step in the process, which is what is currently happening.

**Closed by duncangraham** 2015-08-24 18:01 UTC
